.TH "tio" "1" "29 June 2016"

.SH "NAME"
tio \- a simple TTY terminal I/O application

.SH "SYNOPSIS"
.PP
.B tio
.RI "[" <options> "] " "<tty device>"

.SH "DESCRIPTION"
.PP
.B tio
is a simple TTY terminal application which features a straightforward
commandline interface to easily connect to TTY devices for basic input/output.

.SH "OPTIONS"

.TP
.BR \-b ", " "\-\-baudrate " \fI<bps>

Set baud rate [bps] (default: 115200).
.TP
.BR \-d ", " "\-\-databits 5" | 6 | 7 | 8

Set data bits (default: 8).
.TP
.BR \-f ", " "\-\-flow hard" | soft | none

Set flow control (default: none).
.TP
.BR \-s ", " "\-\-stopbits 1" | 2

Set stop bits (default: 1).
.TP
.BR \-p ", " "\-\-parity odd" | even | none

Set parity (default: none).
.TP
.BR \-o ", " "\-\-output\-delay " \fI<ms>

Set output delay [ms] inserted between each transmitted character (default: 0).
.TP
.BR \-n ", " \-\-no\-autoconnect

Disable automatic connect.

By default tio automatically connects to the provided device if present. If the device is not present it will wait for it to appear and then connect. If the connection is lost (eg. device disconnects) it will wait for the device to reappear and then reconnect.

However, if the
.B \-\-no\-autoconnect
option is provided tio will exit if the device is not present or exit if an established connection is lost.

.TP
.BR \-l ", " "\-\-log " \fI<filename>

Log to file.
.TP
.BR \-v ", " \-\-version

Display program version.
.TP
.BR \-h ", " \-\-help

Display help.

.SH "KEYS"
.PP
.TP 16n
In session, the following key sequences are intercepted as tio commands:
.IP "\fBctrl-t ?"
List available key commands
.IP "\fBctrl-t c"
Show configuration (baudrate, databits, etc.)
.IP "\fBctrl-t l"
Clear screen
.IP "\fBctrl-t q"
Quit
.IP "\fBctrl-t s"
Show statistics (total number of bytes transmitted/received)
.IP "\fBctrl-t t"
Send ctrl-t key code

.SH "EXAMPLES"
.TP
Typical use is without options. For example:

tio /dev/ttyUSB0
.TP
Which corresponds to the commonly used options:

tio \-b 115200 \-d 8 \-f none \-s 1 \-p none /dev/ttyUSB0
.TP
It is recommended to connect serial tty devices by id. For example:

tio /dev/serial/by\-id/usb\-FTDI_TTL232R-3V3_FTGQVXBL\-if00\-port0
.PP
Using serial devices by id ensures that tio automatically reconnects to the
correct serial device if the device is disconnected and then reconnected.

.SH "AUTHOR"
.PP
Written by Martin Lund <martin.lund@keep\-it\-simple.com>.
